---
services:
  ${PYTHON_SCHEDULER_POD}:
    image: ${PYTHON_SCHEDULER_IMAGE}
    restart: unless-stopped
    container_name: ${PYTHON_SCHEDULER_POD}
    environment:
      - TIME_ZONE=${TIME_ZONE}
      - DB_HOST=${MARIADB_POD}
      - DB_ROOT_PASSWD=${SEATABLE_MYSQL_ROOT_PASSWORD}
      - PYTHON_SCHEDULER_AUTH_TOKEN=${PYTHON_SCHEDULER_AUTH_TOKEN}
      - SEATABLE_SERVER_URL=${SEATABLE_SERVER_PROTOCOL}://${SEATABLE_SERVER_HOSTNAME}
      - PYTHON_STARTER_URL=${PYTHON_STARTER_URL:-http://${PYTHON_STARTER_POD}:8080}
      - PYTHON_SCHEDULER_LOG_LEVEL=${PYTHON_SCHEDULER_LOG_LEVEL}
      - DELETE_LOG_DAYS=${DELETE_LOG_DAYS:-30}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - ${SEATABLE_NETWORKS}
      - ${PYTHON_NETWORKS}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pgrep -f 'python3 scheduler.py' && pgrep -f 'python3 flask_server.py'",
        ]
      interval: 20s
      retries: 3
      start_period: 20s
      timeout: 10s

  ${PYTHON_STARTER_POD}:
    image: ${PYTHON_STARTER_IMAGE}
    restart: unless-stopped
    container_name: ${PYTHON_STARTER_POD}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${PYTHON_TRANSFER_DIRECTORY_PATH}:${PYTHON_TRANSFER_DIRECTORY_PATH}"
    environment:
      - PYTHON_SCHEDULER_URL=http://${PYTHON_SCHEDULER_POD}
      - PYTHON_TRANSFER_DIRECTORY=${PYTHON_TRANSFER_DIRECTORY_PATH}
      - PYTHON_RUNNER_IMAGE=${PYTHON_RUNNER_IMAGE}
      - PYTHON_STARTER_LOG_LEVEL=${PYTHON_STARTER_LOG_LEVEL}
    networks:
      - ${PYTHON_NETWORKS}

  ${PYTHON_RUNNER_POD}:
    image: ${PYTHON_RUNNER_IMAGE}
    restart: unless-stopped
    container_name: ${PYTHON_RUNNER_POD}
    networks:
      - ${PYTHON_NETWORKS}

networks:
  ${SEATABLE_NETWORKS}:
    name: ${SEATABLE_NETWORKS}
  ${PYTHON_NETWORKS}:
    name: ${PYTHON_NETWORKS}
